import "./globals.css";
import type { PropsWithChildren } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren<{}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background text-text font-montserrat">
        <div className="max-w-screen-xl mx-auto px-4 py-8 sm:px-6 sm:py-12 md:px-8 md:py-16">{children}</div>
      </body>
    </html>
  );
}
